import turtle
x = float(input("Where would you like the x coordinate of your target? "))
y = float(input("Where would you like the y coordinate of your target? "))
radius = float(input("How big would you like the center circle of the target? "))
turtle.pu()
turtle.goto(x,y)
turtle.pd()
turtle.fillcolor("black")
turtle.pencolor("black")
turtle.begin_fill()
turtle.circle(radius * 4)
turtle.end_fill()
turtle.pu()
turtle.goto(x, y + radius)
turtle.pd()
turtle.fillcolor("teal")
turtle.pencolor("teal")
turtle.begin_fill()
turtle.circle(radius * 3)
turtle.end_fill()
turtle.pu()
turtle.goto(x, y + radius *2)
turtle.pd()
turtle.fillcolor("red")
turtle.pencolor("red")
turtle.begin_fill()
turtle.circle(radius * 2)
turtle.end_fill()
turtle.pu()
turtle.goto(x, y + radius* 3)
turtle.pd()
turtle.fillcolor("yellow")
turtle.pencolor("yellow")
turtle.begin_fill()
turtle.circle(radius)
turtle.end_fill()
turtle.end_fill()
turtle.done() 



